### ISSUE TITLE
Betriebsanweisung zu lang

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/reflow-ofen-einweisung#1]
Wenn die Betriebsanweisung zu lang ist, wird nur die Erste Seite in die Einweisung eingebunden.

Außerdem ist die Anweisung zu lang, das sollte man kürzen.

Ich assigne mal den Toni, weil der genug Verstand hat, das Nötige raus zu fischen ;)

**Comment by sedrubal** [comment]
Cool, die Betreibseinweisung ist nicht mehr zu lang :+1:  aber ist es möglich, sicherzugehen, dass auch mehrere Seiten Betriebseinweisung, falls vorhanden, eingebunden werden? Weil es nur sehr schwer auffällt, wenn nur die erste Seite erscheint.

**Comment by Virtex7** [comment]
Hallo!

meiner Meinung nach, sollte eine Betriebsanweisung nie mehr als eine
Seite haben, daher habe ich mich darum nicht gekümmert.

**Comment by sedrubal** [comment]
ok, dann passt das so.
